import random

n = input('이름을 입력하세요: ')

ans = (
    "seldge",
    "thatcher",
    "smoke",
    "mute",
    "ash",
    "thermite",
    "castle",
    "pulse",
    "twitch",
    "montagne",
    "doc",
    "rook",
    "glaz",
    "fuze",
    "kapkan",
    "tachanka",
    "blitz",
    "iq",
    "jager",
    "bandit",
    "buck",
    "frost",
    "blackbeard",
    "valkiri",
    "capitao",
    "caveira",
    "hibana",
    "echo",
    "jackal",
    "mira",
    "ying",
    "leison",
    "dokkabi",
    "vigil",
    "lion",
    "finka",
    "maestro",
    "alibi",
    "maverick",
    "clash",
    "nomad",
    "kaid",
    "gridrock",
    "mozzie",
    "nokk",
    "warden"
    )

print(n,'은(는) ',ans[random.randint(0,len(ans)-1)],'와 궁합이 ',str(random.randint(0,100)),'점 입니다.')
input('종료하려면 엔터를 누르시오.')
